HathorNetwork/hathor-wallet-mobile

- .travis.yml
The problem we have on Travis is that it's now using `yarn --frozen-lockfile` to install dependencies, whereas before it was just `yarn`. What this parameter does is look if there are dependencies that should be updated on `package-lock.json` and fails if there are.
My fix is forcing Travis to use `npm install` instead. That's what we've been using in our laptops anyway. The only thing to discuss is whether we should do this same `package-lock.json` check. I think we've been "ignoring" this file, so not sure if it's worth doing it.
PS - I'm not sure why Travis is using `yarn` and not `npm`. The default should be `npm`. From their [docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#using-yarn): 
> If both package.json and yarn.lock are present in the current directory, …
> fix: force using npm install in travis

- package-lock.json
- src/App.js
- src/screens/Dashboard.js
Several essential methods for the wallet were being executed in `src/screens/Dashboard.js`, even though they were not related to this screen.
> refactor/essential-methods: move methods from screen/Dashboard.js to App.js

- src/reducer.js
Closes #54: Wallet is taking too long to open after downloading all transactions
The problem was an `O(n^2)` algorithm, where `n` is the number of transactions in the history.
> fix(history): Loading history was too slow

- src/screens/CreateTokenConfirm.js
When creating a new token, the token should be registered automatically and this information should persist after wallet reloads
> fix: new token information missing after re-open

- package-lock.json
- package.json
- The wallet mobile should use the v0.32.1 @hathor/wallet-lib
> chore: upgrade wallet lib to v0.32.1

- package-lock.json
- package.json
- Wallet-lib should be upgraded to v0.33.0
> chore: upgraded wallet-lib to v0.33.0

- src/components/AmountTextInput.js
- src/screens/SendAmountInput.js
We've added a `flex: 1` to the AmountInput component to fix a bug in the android app in the SendAmountInput screen when deleting all the text (the bug is described here https://github.com/facebook/react-native/issues/30666).
This fix ended up breaking many screens in all devices (this can be seen in the videos added in this PR https://github.com/HathorNetwork/hathor-wallet-mobile/pull/168 or in the images below). 
The fix was to remove the generic `flex: 1` and add it as a custom style only for the SendAmountInput screen. This makes all the screens to work in both android and iOS.
- All screens should have the UI working fine, including the TextInput in the SendAmountInput screen in the android.
Bug in iOS:
Bug in Android:
Correct screen after the fix:
> fix: UI in many screens was broken because of flex 1

- src/App.js
- src/components/QRCodeReader.js
The method `removeEventListener` in the `AppState` was deprecated but was raising an error when using the QRCode.
React native documentation: https://reactnative.dev/docs/appstate#removeeventlistener
Error:
- The AppState remove listener method won't use the deprecated one anymore and the QRCode reader will continue working fine.
> fix: old remove event listener syntax was raising an error

- src/sagas/wallet.js
- Token metadata should download without blocking the `loadTokens` generator
> fix: use spawn instead of fork

- src/sagas/wallet.js
- When a transaction is received in real-time, we should only download tokens that are going to (or from) an address that belongs to the current loaded wallet
> feat: only download wallet tokens

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/build.gradle
- android/gradle.properties
- ios/HathorMobile.xcodeproj/project.pbxproj
- ios/HathorMobile/Info.plist
- package-lock.json
- package.json
- Fixes https://github.com/HathorNetwork/hathor-wallet-mobile/issues/224
- Increased the memory pool for gradle to 4096M to fix the error described [here](https://github.com/facebook/react-native/issues/35168)
- Added a new flag on `AndroidManifest.xml` to indicate that the app can't be started from other apps (we are currently not using this for anything)
- Added a flag in info.plist to fix https://github.com/HathorNetwork/hathor-wallet-mobile/issues/226
- Bumps the version to v0.21.1
> chore: bump v0.21.1 and other release related fixes

- locale/da/texts.po
- locale/pt-br/texts.po
- locale/ru-ru/texts.po
- locale/texts.pot
- src/actions.js
- src/components/ReceiveMyAddress.js
- src/reducer.js
- src/sagas/wallet.js
- src/screens/Settings.js
After the refactor done in https://github.com/HathorNetwork/hathor-wallet-mobile/pull/232, the wallet stopped reloading after a websocket reconnection.
The initial problem was that we were not setting the `walletStartedState` to `LOADING`, which made it reload the wallet but never display the loading screen.
But not only that, since we refactored the loading flow, the reload was still not happening. Upon investigation, I found out that the old mechanism for reloading the wallet was only working because the `LoadHistoryScreen` was dispatching the `startWalletRequested` action on the `componentDidUpdate`, as we can see [here](https://github.com/HathorNetwork/hathor-wallet-mobile/pull/232/files#diff-6b628a954cc3611565a6b19e839717bb5431913b6d02c38206de52df4b355fbbL55).
- We should reload the …
> fix: wallet not reloading data after a reconnect and wallet reset after an error

- locale/da/texts.po
- Danish time should be formatted correctly
> fix: time in danish had a space between the HH and mm

- src/constants.js
- src/featureFlags.js
- src/sagas/wallet.js
Today we have multiple feature flags for the wallet-service mobile wallets:
* `wallet-service-mobile-ios-testnet.rollout`
* `wallet-service-mobile-ios-mainnet.rollout`
* `wallet-service-mobile-android-mainnet.rollout`
* `wallet-service-mobile-android-testnet.rollout`
The idea is to refactor this, to have a single feature flag `wallet-service-mobile.rollout` for both mobile wallets and use the new `constraints` mechanism from unleash to set the rollout percentages
Here is an example of a configured feature flag with this new mechanism:
- We should use unleash's `properties` attribute while setting context for the unleash client to be able to fine control our unleash feature strategies
> refactor: new feature flag schema

- src/sagas/wallet.js
- src/screens/LoadWalletErrorScreen.js
- src/screens/PinScreen.js
This improves the wallet load time by starting the wallet from the stored xpriv instead of generating them again during the loading step
During the investigation of why the wallet was taking up to 11s to load, I ran a benchmark on the methods the lib calls during initialization and found two bottlenecks:
| Method | Time (seconds) |
| --- | --- |
| generateCreateWalletAuthData | 5.401s |
| executeGenerateWallet | 2.453s |
Something interesting to notice is that when the debugger is activated, those methods are up to 40× faster and that's why it was so hard to figure out:
| Method | Time (seconds) |
| --- | --- |
| generateCreateWalletAuthData | 0.357s |
| executeGenerateWallet | 0.145s |
Apparently, when the debugger is activated, it changes the default javascript runtime to v8 (the one …
> refactor: load from xpriv

- QA.md
- src/App.js
- src/actions.js
- src/reducer.js
- src/sagas/helpers.js
- src/sagas/pushNotification.js
- src/screens/PinScreen.js
- src/screens/ResetWallet.js
- Avoid transaction details modal (balance modal) to appear over lock screen. With this fix the modal will only appear after unlock the screen.
Regarding the previous approach to render the reset page from the pin screen:
> The previous approach unlocks the wallet and navigates to ResetWallet
> screen with a back button pointing to StartWalletLockScreen,
> this interfering with the stack navigation.
> fix: tx details modal over lock screen

- src/App.js
- src/reducer.js
- src/sagas/featureToggle.js
- src/sagas/wallet.js
- src/screens/ChoosePinScreen.js
- src/store.js
- When restarting the wallet we should fully clean any persisted data
- The feature toggle cleanup was interfering with the wallet reset
- Loading the tokens into redux should not use "for await" 
- Remove unnecessary copy of the storage instance.
> fix: wallet reset cleanup

- android/app/_BUCK
- android/app/src/debug/java/com/hathormobile/ReactNativeFlipper.java
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/hathormobile/MainActivity.java
- android/app/src/main/java/com/hathormobile/MainApplication.java
- android/app/src/main/java/com/hathormobile/ReactInstanceHolder.java
There are currently two application ids on the android native files. This causes the application not to open correctly on `npm run android` command.
- Application id should be unified across all native files
> fix: unifies application id name

- package-lock.json
- package.json
- The mobile wallet should use the Wallet Lib version `1.0.0-rc8`
> chore: Bump lib to rc-8

- src/App.js
The "Welcome" screen was being rendered while the storage fetched information about the loaded wallet. A blank screen should be shown instead, to avoid content flickering.
- Nothing should be rendered until the application decides whether the Wallet is loaded or not
> fix: Initial screen rendering

- src/components/NewPaymentRequest.js
- src/components/TokenSelect.js
- src/screens/ChangeToken.js
- src/screens/SendAmountInput.js
Since the upgrade to navigation v5, some screen navigations trigger a [`Non-serializable values were found in the navigation state`](https://reactnavigation.org/docs/troubleshooting/#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state) alert.
The solution for this was to remove callbacks from the `ChooseToken` screen and replace it with existing saga flows:
- The `onItemPressed` callback function passed as `prop` was removed
- The `ChooseToken` screen updates directly the `selectedToken` redux state
- The screens that call it listen to that update directly from the state
- All navigation parameters on the app should be serializable
> refactor: Remove callback from screen nav params

- src/screens/PinScreen.js
By navigating back and forth on the PIN Screen while having the Biometry activated, sometimes the PIN Screen would be misaligned.
By duplicating some style restraints into the newly added `renderPinDigits()` helper method this behavior no longer appears.
- Pin Screen should be aligned in all cases
Before ( when incorrect alignment is rendered ), After ( fixed behavior )
> fix: pin screen labels alignment

- android/build.gradle
- update the manifest to targed the api level 33
The only behavior affected by this API level is the [granular media-permission](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions), however the default behavior provided by the platform is good enough.
Closes: #315
> chore: update api level to 33

- src/sagas/pushNotification.js
- We should clean the FCM device token only if it's registered.
> fix: validating if device is registered in the FCM before resetting the push notification

- src/App.js
- src/components/AmountTextInput.js
- src/components/HathorHeader.js
- src/components/ModalConfirmation.js
- src/components/ReceiveMyAddress.js
- src/constants.js
- src/screens/CreateTokenAmount.js
- src/screens/CreateTokenConfirm.js
- src/screens/CreateTokenName.js
- src/screens/CreateTokenSymbol.js
- src/screens/PaymentRequestDetail.js
- src/screens/PinScreen.js
- src/utils.js
Solves items from #318 
- Navigating to the "Receive" screen no longer marks an address as used
- "Receive Amount" screen automatically focuses on the Keyboard
- Clicking the "X" on the "Create Token" flow goes back to the dashboard screen
- Clicking "Back" on the "Receive Transaction Details" after receiving a tx, goes back to the dashboard screen
- Correct positioning of the "Receive Transaction Details" confirmation modal
- Correct "Safe Area" insets for modals
- Correct "Safe Area" insets for when the keyboard is being displayed
- Dismisses keyboard whenever the "Pin Screen" is displayed
Tested on simulators for devices:
- iPhone 13 mini
- iPhone 13
- iPhone SE (3rd gen)
- iPhone 14 Pro
> Fix: Issues raised on iOS QA

- .github/dependabot.yml
- Gemfile.lock
- README.md
- All suggestions from DependaBot should be implemented
- Default branch to be watched by DependaBot changed to `dev`
- #184
- #246
- Added protection for dangerous characters in names of tags and attributes
- Avoids regex backtracking
- [1.4.0 -> 1.5.0](https://my.diffend.io/gems/cocoapods-downloader/1.4.0/1.5.0) - Branch encoding fix ( and patch on [1.5.1](https://my.diffend.io/gems/cocoapods-downloader/1.5.0/1.5.1) )
- [1.5.1 -> 1.6.0](https://my.diffend.io/gems/cocoapods-downloader/1.5.1/1.6.0) - Protection against command injection ( and patches [1.6.1](https://my.diffend.io/gems/cocoapods-downloader/1.6.0/1.6.1), [1.6.2](https://my.diffend.io/gems/cocoapods-downloader/1.6.1/1.6.2) and [1.6.3](https://my.diffend.io/gems/cocoapods-downloader/1.6.2/1.6.3) refactoring and documenting …
> chore: Dependabot suggested updates

- __tests__/sagas/networkSettings.test.ts
- src/constants.js
- src/sagas/helpers.js
- src/sagas/networkSettings.js
- src/sagas/pushNotification.js
- src/sagas/wallet.js
- src/sagas/walletConnect.js
- src/store.js
- Replaces network constants by the networkSettings either from app storage or redux state.
The change here should not affect the wallet's operation.
> (2) refactor: constants settings to networkSettings state

- src/components/PublicExplorerListButton.js
- src/utils.js
- Use the networkSettings.explorerUrl as the link to the explorer button.
> (3) refactor: hardcoded explorer link to networkSettings explorerUrl

- src/components/HathorList.js
- src/screens/Settings.js
The following change is related to this ["Settings page"](https://github.com/HathorNetwork/rfcs/blob/32b9677253c69dcd3ef3eba6958df89d245d381a/projects/hathor-wallet-mobile/0001-dev-settings.md#1-settings-page) topic in the design.
- Add title to HathorList
- Refactor Settings page by declaring HathorList with "General Settings" title
> (4) feat: Add title to HathorList and refactor Settings page

- .github/dependabot.yml
After adding the Dependabot configuration YML on #340 , subsequent PRs started [displaying errors on the CI](https://github.com/HathorNetwork/hathor-wallet-mobile/pull/354/checks?check_run_id=18043140921) due to incorrect configuration:
```
The property '#/updates' of type object did not match the following type: array
```
While fixing it, by just adding the missing `-` character on the YML, I also noticed [on the docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch) other properties that could be useful to us, such as personalized labels. So, this PR also adds these other properties.
- The Dependabot must run correctly on the `dev` branch
> fix: Dependabot yml file structure

- src/screens/PinScreen.js
Currently we are displaying a blank screen while the faceid is being asked and only displaying the PIN when it's successful or cancelled, the expected behavior is to display the face id indicator on top of the pin screen
- Remove the logic that hides the PIN while the faceid is being requested
> refactor: remove blank on pin screen

- locale/da/texts.po
- locale/pt-br/texts.po
- locale/ru-ru/texts.po
- locale/texts.pot
- src/sagas/wallet.js
- src/screens/LoadWalletErrorScreen.js
- Fix error handling when starting wallet on fullnode
- Add reset button in the `LoadWalletErrorScreen`
- Update localization base text and translate to pt-br
Related to [Infinity load when the network version can't be verified](https://github.com/HathorNetwork/hathor-wallet-mobile/issues/364), which is fixed in the lib by https://github.com/HathorNetwork/hathor-wallet-lib/pull/584.
>[!WARNING]
>I left empty all the translations related to WalletConnect and DevSettings because it is being handled in another PR.
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/e009b320-4393-412b-9c81-ec66687889d6
> fix: wallet start error when running on fullnode

- __tests__/sagas/networkSettings.test.ts
- src/actions.js
- src/components/NetworkSettings/NetworkStatusBar.js
- src/constants.js
- src/reducers/reducer.js
- src/sagas/helpers.js
- src/sagas/networkSettings.js
- src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
- src/screens/NetworkSettings/NetworkPreSettingsScreen.js
- src/screens/NetworkSettings/NetworkSettingsFlowStack.js
- src/screens/NetworkSettings/helper.js
This PR aims to improve the Network Settings Actions by decomposing it in actions that conveys a better semantic.
- rename action to NETWORKSETTINGS_UPDATE_REQUEST
- add action NETWORKSETTINGS_UPDATE_STATE
- add action NETWORKSETTINGS_PERSIST_STORE
- add action NETWORKSETTINGS_UPDATE_WAITING
- refactor action NETWORKSETTINGS_UPDATE_SUCCESS
- refactor action NETWORKSETTINGS_UPDATE_INVALID
- refactor action NETWORKSETTINGS_UPDATE_FAILURE
- add docstring to action NETWORKSETTINGS_UPDATE_READY
- refactor NetworkStatusBar
- refactor saga effect persistNetworkSettings
- resolve all the lint issues
>[!WARNING]
>The following video has a legacy behavior when showing the network status bar alert for mainnet settings when removing only the wallet service URLs fields. This bar should show up only if …
> (15) refactor: network settings actions

- src/screens/PinScreen.js
This is related to a bug reported on #318.
The OS keyboard was being incorrectly displayed on the Pin Screen in specific situations where the application had been stopped while showing the OS keyboard.
- The OS keyboard should never be displayed on the PinScreen
To test the results of this fix:
- Open the app with a loaded wallet
- Navigate to "Receive" and then "Payment Request"
- Insert an amount and keep the numeric keyboard active
- Send the app to background
- Wait for 5 minutes
- Switch back to the app
- The Pin Screen should be displayed _without_ the OS Keyboard overlay
> fix: Closes keyboard on PinScreen

- package-lock.json
- package.json
After successfully upgrading React Native to version 0.72 on #342 , the build stopped working on iOS due to [an incompatibility](https://github.com/software-mansion/react-native-reanimated/issues/4522#issuecomment-1738652919) with the `react-native-reanimated` version 2.17.0.
This PR upgrades this dependency to version `3.5.4`, which [claims to have no breaking changes](https://github.com/software-mansion/react-native-reanimated/releases/tag/3.0.0) from version `2.17.0`: it is only [an upgrade to support the React Native New Architecture](https://blog.swmansion.com/releasing-reanimated-3-0-17fab4cb2394#a63b). It also has less dependencies that its predecessor, alleviating the lockfile.
- Upgrades the `react-native-reanimated` to a version compatible with React Native v0.72
> chore: Update `react-native-reanimated`

- locale/texts.pot
- src/components/NetworkSettings/NetworkStatusBar.js
- src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
- src/screens/NetworkSettings/NetworkSettingsDisclaimerScreen.js
- src/styles/themes.js
- Keep consistency with other components colors
- Remove unused colors
>[!NOTE]
>This PR complies with the designer decision. See the [discussion](https://github.com/HathorNetwork/hathor-wallet-mobile/pull/356#issuecomment-1787390696).
Alert color on network status bar:
> (17) refactor: AlertUI color

- src/store.js
In a specific update condition, the app would not accept the user's PIN code:
- The user should have a wallet on and already installed `v0.25.0` app
- This wallet should have no registered custom tokens, only HTR
- The user upgrades to `v0.26.0-rc7`
- The Pin Screen does not accept the valid Pin anymore
This would happen because the migration code expected registered custom tokens to be present. This PR fixes this.
- The app should accept the user's old PIN after migration on the identified edge case
> Fix: Pin not working on update

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/feature_branch_pr_template.md
- .github/PULL_REQUEST_TEMPLATE/version_bump_pr_template.md
- We should have a default PR template with links to two PR templates -- the version bump and the feature branch PR templates
- The version bump PR template should have a checklist for when creating a version bump in the wallet-mobile
> chore: version bump pr template

- locale/da/texts.po
- locale/pt-br/texts.po
- locale/ru-ru/texts.po
- locale/texts.pot
- src/constants.js
- src/sagas/networkSettings.js
- src/screens/SendAddressInput.js
- src/store.js
- src/utils.js
- Change the component class to component function
- Extend validateAddress utility function to receive the network as
second argument
- Get the network from redux state
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/cbcc9e2a-861f-4301-b971-fd61c4d079e3
> fix: component SendAddressInput

- src/sagas/helpers.js
- src/sagas/pushNotification.js
- src/screens/SendScanQRCode.js
In two places the application was trying to check if a token was registered by querying the wallet storage object directly. However, this low level storage does not contain the default token, and that lead to false negative responses.
There are other higher level _helper_ sources that already take these implicit default tokens into consideration: those should be used instead. Namely, the `getRegisteredTokens` saga helper function and the redux state `tokens` property.
- Registered tokens should be read from the helper functions
> Fix: QR Code registered token check

- src/screens/SendScanQRCode.js
Multiple alerts were being shown one over the other when the user tried to scan a QR Code and an error was raised.
- Only one alert should be shown when an error occurs on Send Tokens
> fix: multiple alerts shown to QR reading

- QA.md
Recently we found some errors ( fixed by #384 and #386 ) that only happened during QR Code scanning. This procedure should also be on the main QA.
- There should be steps to validate the functionality of the QR Code Scanner
> Docs: QA steps to validate QR Code scanner

- android/app/build.gradle
- ios/HathorMobile.xcodeproj/project.pbxproj
- package-lock.json
- package.json
> Chore: Bump version to `v0.26.1`

- src/screens/CreateTokenAmount.js
- src/screens/Receive.js
- src/screens/SendAmountInput.js
As described in #402 , the user is unable to close the numeric keyboard on iOS. On some occasions this causes a bad user experience.
This PR fixes this by adding a press event handler on the screens that exhibit a numeric keyboard.
- The user should be able to close the numeric keyboard on iOS
- Fixes #402
> [!TIP] 
> In total, just a few lines had actual text modified. The rest of the modified lines were only due to indentation adjustments.
> To better visualize the actual changes I suggest using the "Hide whitespace" feature on GitHub, as it highlights only the words that were changed on this file, and not the indentation adjustments that were necessary:
>
> ![Ignore Whitespace Diff](https://github.com/HathorNetwork/hathor-wallet/assets/1299409/1b603254-b05e-4698-80bb-c6360fd227c0) …
> Feat: Allow user to close numeric keyboard on iOS

- scripts/check_version
- CI should correctly validate all release candidate version declarations on the app
- Fixes #375
> fix: Release candidate version checker on CI

- src/sagas/featureToggle.js
- We should send the `appVersion` to Unleash so we can filter users depending on their versions
> feat: sending appVersion as a property on unleash

- flake.lock
- flake.nix
- Updated flake nixpkgs input on flake.lock
- Updated nodejs on flake.nix to v18
> chore: flake update nodejs

- src/sagas/pushNotification.js
- fix: PinScreen dismiss response
- fix: exits script after dispatch failure effect
- fix: replace BLOCKED to DENIED enum value
- fix: push notification authorization logic
PinScreen response latency now in miliseconds:
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/97403ac8-0cf8-4cf3-b24a-d688483d5858
Closes: https://github.com/HathorNetwork/hathor-wallet-mobile/issues/415
---
We have 2 major offenders:
- `generateAccessDataFromSeed` consuming ~4s
- `generateCreateWalletAuthData` consuming ~14s
Under `generateCreateWalletAuthData` we have other 3 offenders:
- `getXPrivKeyFromSeed` using ~4s
- `getXPubKeyFromSeed` using ~4s
- `getAuthXPubKeyFromSeed` using ~4s
Both `getXPubKeyFromSeed` and `getAuthXPubKeyFromSeed` calls `getXPrivKeyFromSeed` under the hood, which …
> fix: push notification registration latency on PinScreen

- package-lock.json
- package.json
- src/sagas/featureToggle.js
- We should use the hathor unleash client instead of the official unleash client
> refactor: feature toggle using hathor unleash client

- src/components/AskForPushNotification.js
- src/sagas/pushNotification.js
- fix: push notification opt-in modal render time
- chore: improve code readability
Opt-in renders after wallet becomes ready:
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/1ca68243-002f-4d3c-9bb2-37ec4b5e6e81
Closes: https://github.com/HathorNetwork/hathor-wallet-mobile/issues/416
> fix: opt-in modal render time

- src/App.js
- src/actions.js
- src/components/TokenSelect.js
- src/config.js
- src/constants.js
- src/reducers/reducer.js
- src/sagas/helpers.js
- src/sagas/tokens.js
- src/sagas/wallet.js
- src/screens/UnregisterToken.js
Closes: https://github.com/HathorNetwork/internal-issues/issues/242
@pedroferreira1 has investigated the these of migration be the culprit and has confirmed it. See the [investigation note](https://github.com/HathorNetwork/internal-issues/issues/242#issuecomment-1971507971).
Despite we didn't need a fix anymore, we will proceed to avoid this problem in the future.
- Should fix token duplication by replacing token list to token map
The following recording shows operations with token, register, unregister and creation to demonstrate these operations were not effected by the fix/refactoring:
<video src="https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/4b03af1c-6d0c-451d-98d1-6846c2040163"></video>
> fix: token duplication on dashboard

- src/sagas/tokens.js
- src/sagas/wallet.js
Closes https://github.com/HathorNetwork/internal-issues/issues/257
- should show all transactions after reload, including the ones that could possibly be lost during the reload
- This is possible by forcing download of HTR history
> fix: missing transaction after reload

- src/sagas/wallet.js
- Filter HTR when fetching token metadata
> feat: filter HTR out when fetching token metadata

- locale/da/texts.po
- locale/pt-br/texts.po
- locale/ru-ru/texts.po
- locale/texts.pot
- src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
- src/screens/NetworkSettings/NetworkPreSettingsScreen.js
- src/screens/NetworkSettings/helper.js
- Should add a scroll for custom network settings form, to avoid overflow of elements in the screen
- Should add a padding to keep the field on screen when the keyboard is open over the field
- Should add form validation for wallet-service fields, to avoid errors on saga processing
- If any of the wallet-service fields are filled, then all the fields should be filled, otherwise an invalid error should appear in the empty field
- if all the wallet-service fields are filled, or none are filled, then the form is allowed to be sent
It resolves: https://github.com/HathorNetwork/hathor-wallet-mobile/issues/458
iOS
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/f861f1a2-e26a-4754-85a3-25c729c60666
Android
[custom-network-settings-android.webm](https://github.com/HathorNetwor …
> fix: custom network settings form

- src/sagas/wallet.js
- It should fix wallet-service usage when it should not be used: when a user empty wallet service URL
> fix: useWalletService by forcefully disabling it when wallet service URL is empty

- src/utils.js
- It should disable the Push Notification settings if Wallet Service URL is empty
- It should closes https://github.com/HathorNetwork/internal-issues/issues/287
> fix: disable push notification if wallet service url is empty

- src/utils.js
- It should add a condition to allow use the push notification settings only when using the mainnet network
- It should closes https://github.com/HathorNetwork/internal-issues/issues/285
> fix: allows push notification settings only when using mainnet network

- locale/da/texts.po
- locale/pt-br/texts.po
- locale/ru-ru/texts.po
- locale/texts.pot
- src/actions.js
- src/components/Icons/constants.js
- src/components/Icons/helper.js
- src/components/PublicExplorerListButton.js
- src/components/SimpleButton.js
- src/components/TokenSelect.js
- src/components/TxDetailsModal.js
- src/models.js
- src/reducers/reducer.js
- src/sagas/nanoContract.js
- src/sagas/tokens.js
- src/screens/MainScreen.js
- src/styles/themes.js
- src/utils.js
This change enables to show nano contract context information on regular transaction list and details. Also, it enables to set marks based on transaction type and make visual differentiation among them.
Look at the approved design https://github.com/HathorNetwork/hathor-wallet-mobile/issues/445. Go to "Flow 4".
- should extract TxHistory construction to the model
- should add nano contract information on tx details view
- should change icon to access token info
---
>[!NOTE]
>It depends on:
>- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/453
>- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/454
>- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/432
>- https://github.com/HathorNetwork/hathor-wallet-lib/pull/630
> feat: add nano contract info to tx history [6]

- src/sagas/networkSettings.js
- src/store.js
- It should remove registered tokens when a user changes the network settings
- It should closes https://github.com/HathorNetwork/internal-issues/issues/286
It depends on:
- https://github.com/HathorNetwork/hathor-wallet-lib/pull/648
> fix: remove registered tokens when changing network settings

- src/store.js
- We need to call the store's super methods on write operations to avoid errors due to inconsistent storage state.
> chore: call super method on write

- __tests__/sagas/nanoContracts/fixtures.js
- __tests__/sagas/nanoContracts/historyNanoContract.test.js
- __tests__/sagas/nanoContracts/registerNanoContract.test.js
- src/actions.js
- src/reducers/reducer.js
- src/sagas/nanoContract.js
- src/store.js
This is a PR on a sequence to make the review easier.
- It should implement the unregister saga effect for nano contract
- It should add unregisterNanoContract to HybridStore
- It should clean registered nano contracts on cleanTokens
- It should update payload of `nanoContractAddressChangeRequest` action
- It should implement reducer `onNanoContractAddressChangeRequest`
>[!NOTE]
>It depends on:
>- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/455
>- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/456
> feat: add unregister nano contract saga effect [10]

- android/app/build.gradle
- ios/HathorMobile.xcodeproj/project.pbxproj
- package-lock.json
- package.json
- This bump aims to fix an error on version parsing on iOS
> bump: 0.27.1

- package-lock.json
- package.json
- it should bump wallet-lib dependency to version 1.6.0
> chore: bump wallet-lib to v1.6.0 [15]

- flake.lock
- flake.nix
- We should update nodejs in `flake.nix` to v20
- We should update all flake inputs (fixed versions in flake.lock)
> chore: updated flake and nodejs version

- src/reducers/reducer.js
- It should set nanoContract redux state to its initial state after reload be requested
When we change the network settings, all registered tokens and nano-contracts are cleaned from storage, therefore the redux state should also resumes to its initial state.
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/a3a1ed83-20c1-4598-93ab-7040f8bddeca
> fix: cleaning of tokens and nano-contract registered after reload

- src/screens/SendScanQRCode.js
I have fixed token duplication on the Dashboard screen by transforming the registered tokens list into a map, this way we would never have a duplication. However, I failed to cover the necessary change and left one case untouched, which caused this bug.
See the previous fix at: https://github.com/HathorNetwork/hathor-wallet-mobile/pull/431
- It should restore the ability to read QR code when sending token
Closes: https://github.com/HathorNetwork/internal-issues/issues/345
> fix: Unable to send token by reading a QR code

- src/App.js
- src/components/ShowPushNotificationTxDetails.js
- src/constants.js
- src/sagas/pushNotification.js
- src/screens/Dashboard.js
- src/screens/SendScanQRCode.js
- It should make tx details modal open over any screen
- It should make tx details modal open after a simple unlock without a relead
[fix-unable-to-open-tx-modal-on-any-screen.webm](https://github.com/user-attachments/assets/8de0cedf-0875-42f5-a09b-d4c15821122b)
Closes: https://github.com/HathorNetwork/internal-issues/issues/346
> fix: unable to open push notification details modal over any screen

- src/components/NanoContract/NanoContractTransactionActionList.js
- src/components/NanoContract/NanoContractTransactionActionListItem.js
- src/components/NanoContract/NanoContractTransactionHeader.js
- src/constants.js
- src/reducers/reducer.js
- src/sagas/nanoContract.js
- src/screens/NanoContract/NanoContractTransactionScreen.js
- It should add actions list to Nano Contract Transaction Screen
- It should add actions to each nano contract history transaction object
- It should improve reducer documentation
- It should restore header capability to shrink
Closes: https://github.com/HathorNetwork/hathor-wallet-mobile/issues/518
https://github.com/user-attachments/assets/d11c0fed-1d8b-4aa3-ba6d-ae79e00e5a6e
> feat: add nano-contract transaction actions

- package-lock.json
- package.json
- src/sagas/networkSettings.js
- Replace the network logic on sagas/networkSettings by the lib method getNetworkFromFullNodeNetwork
- Update the lib version to v1.9.0
Closes: https://github.com/HathorNetwork/hathor-wallet-mobile/issues/521
> refactor: replace network identification logic by the lib method

- locale/da/texts.po
- locale/pt-br/texts.po
- locale/ru-ru/texts.po
- locale/texts.pot
- src/actions.js
- src/components/NanoContract/NanoContractDetails.js
- src/reducers/reducer.js
- src/sagas/nanoContract.js
- src/utils.js
- It should fix nano contract transaction loading for newer transactions
- Add 'Load More' in the footer of transactions list, which triggers the request for older transactions when pressed
- Hides the 'Load More' button when the last transaction of the list is the 'initialize'
https://github.com/user-attachments/assets/781e6759-6db2-4e81-b3bc-c20641c097ed
https://github.com/user-attachments/assets/68f99f4e-b8be-4cf2-a02f-63f1268bfa18
The video above shows a list of transactions initialized with the newest transaction only. When the button 'Load More' is pressed a list of older transactions is loaded. The button 'Load More' didn't show after load because the list has reached its end.
---
Related issues:
---
> fix: nano-contract history pagination and list order

- locale/da/texts.po
- locale/pt-br/texts.po
- locale/ru-ru/texts.po
- locale/texts.pot
- src/App.js
- src/components/NanoContract/RegisterNewNanoContractButton.js
- src/screens/NanoContract/NanoContractRegisterScreen.js
- src/screens/NanoContractRegisterQrCodeScreen.js
- It should create a navigation stack to contain:
- A screen to read QR Code
- A screen to inform the nano contract to register, which should be fulfilled by QR Code value read
- A screen to ask camera permission
- It should create a screen to read QR Code of Nano Contract ID
- It should adjust the NanoContractRegisterScreen to make it accept a Nano Contract ID on its route param
Registering Nano Contract by QR Code reading:
https://github.com/user-attachments/assets/fe5ba910-3416-493c-822d-dab7547b2336
Closes: https://github.com/HathorNetwork/hathor-wallet-mobile/issues/519
> feat: add qr code to register nano contract

- src/components/NewHathorButton.js
- src/components/WalletConnect/NanoContract/NewNanoContractTransactionRequest.js
- Allow the user to register the nano contract when a RPC request from a unregistered nano contract arrives
https://github.com/user-attachments/assets/d5336a8f-96ba-4fcc-863f-cb068e14b3b0
It allows user to register and after it the transaction request is loaded.
https://github.com/user-attachments/assets/c15742b6-b475-47e3-ba97-7026bd6754c3
It allows user only to decline the transaction and go back as a feedback action.
>[!NOTE]
>This is a good candidate to go to production.
> feat: add register nano contract buttom if nc not registered on new nc transaction

- locale/da/texts.po
- locale/pt-br/texts.po
- locale/ru-ru/texts.po
- locale/texts.pot
- src/sagas/nanoContract.js
- Replace call to nano contract state by other call to get nano contract information
This is important because the "/state" endpoint is not consistent as it can return "not found" while the new nano contract was not confirmed by a block.
Closes: https://github.com/HathorNetwork/hathor-wallet-mobile/issues/510
> refactor: replace nano contract state call for history call

- src/config.js
- src/screens/InitWallet.js
- We should skip the seed confirmation depending on a constant file in config
I think this could go to `master` (changing the default to `true`), as it is a nice option to have on whitelabel apps, but we would have to add a mechanism for display the seed after it's loaded
> refactor: skip directly to the ChoosePinScreen

- package-lock.json
- package.json
- src/components/NewHathorButton.js
- src/components/TxDetailsModal.js
- src/components/WalletConnect/NanoContract/NewNanoContractTransactionRequest.js
- src/config.js
- src/constants.js
- src/reducers/reducer.js
- src/sagas/walletConnect.js
- src/screens/InitWallet.js
- src/screens/NetworkSettings/NetworkPreSettingsScreen.js
- We should include the nano testnet settings and default to it.
- We should allow the user to select the nano testnet in the network settings screen
> refactor: default network is nano testnet

- package-lock.json
- package.json
- src/components/WalletConnect/NanoContract/NanoContractMethodArgs.js
- src/utils.js
- Provide a better parsing for argument value taking in consideration the custom type
> feat: parse argument value by custom type

- android/build.gradle
- The application build process should target Android SDK 34
The application build was run on Ubuntu 22, with the following devices working successfully
- Emulator running Android 13
- Motorola G52 physical device running Android 13
- Emulator running Android 15
To ensure the build was being executed in an environment as reproducible as possible, the following cache clearing script was used:
```sh
#!/bin/bash
rm -rf /home/my_user/Android/Sdk/ndk/*
rm -rf /home/my_user/mobile-wallet/android/.gradle
rm -rf /home/my_user/mobile-wallet/android/build
rm -rf /home/my_user/mobile-wallet/android/app/build
cd ~/mobile-wallet/android
./gradlew --stop
pkill -9 -f gradle
cd ~/
```
> feat: Bumps Android target SDK to 34

- package-lock.json
- package.json
- src/reducers/reducer.js
An order from newest to oldest improves user experience.
- Sort nano contracts by last registered first
- Upgrade hathor-rpc-handler lib to 0.0.2-experimental-alpha
The new registered Nano Contract is presented first in the list:
https://github.com/user-attachments/assets/1750cb75-79ef-4057-a52a-a5de08d8f2a0
> refactor: sort nano contracts by last registered first

- src/sagas/helpers.js
- src/sagas/nanoContract.js
- feat: add safeEffect as a saga helper
- feat: wrap registerNanoContract effect on safeEffect
Issue: https://github.com/HathorNetwork/hathor-wallet-mobile/issues/550
>[!NOTE]
>This PR can be cherry-picked to [refactor/default-network](https://github.com/HathorNetwork/hathor-wallet-mobile/tree/refactor/default-network) branch.
> feat: add safe effect helper

- src/sagas/walletConnect.js
- We should use `actionChannel` to keep a queue of `WC_SESSION_REQUEST` actions
- We should stop using `takeLeading` as it will skip actions
- We should be able to process requests in series
> fix: session request queue

- src/components/WalletConnect/NanoContract/NanoContractExecInfo.js
- src/components/WalletConnect/NanoContract/NewNanoContractTransactionRequest.js
- Fix empty caller after register nano contract
- Fix empty caller after define first address while nano contract is not registered
- Remove dependency on `initialize` call on `NanoContractExecInfo` component
- Shows caller address not determined feedback asking user to select one when caller address is empty or first address request fails
https://github.com/user-attachments/assets/8e9798ec-ba48-47f0-bfb0-e3599ea4c13a
https://github.com/user-attachments/assets/ee0d971b-8b1d-4687-b839-ae7a59b7a12b
The following screenshot simulates the caller empty, it is very unlikely to happen now.
> fix: empty caller after define first address

- src/actions.js
- src/components/WalletConnect/NanoContract/NewNanoContractTransactionRequest.js
- src/constants.js
- src/reducers/reducer.js
- src/sagas/tokens.js
- src/utils.js
The user needs the data as quick as possible in a new nano contract request. To achieve this requirement we can make the http request concurrent, however we should respect the rate-limit rules set in public node endpoints.
- Make requestUnregisteredTokens to call token details in "parallel"
- Add an action to end the request unregistered tokens process
- Add an utility function to split a list in groups
We can implement a client object that implements a more sophisticated limit-rate strategy that adapts to back pressure from server. This control is interesting to pursuit in order to better rationalize the resources at app disposal and at the same time helps the server to heal in case of spike usage.
>[!NOTE]
>It closes https://github.com/HathorNetwork/hathor-wallet-mobile/issues/531. …
> feat: make requestUnregisteredTokens concurrent

- src/sagas/nanoContract.js
- src/utils.js
This PR closes https://github.com/HathorNetwork/hathor-wallet-mobile/issues/514 to add concurrency on isAddressMine calls without mess with history ordering.
- Refactor fetchHistory to avoid iteration suspension while hydrating the NcTxHistory item with isMine flag
- As the isAddressMine is an O(1) call and don't require a http request, we can use a plain Promise.all to collect the tasks
https://github.com/user-attachments/assets/fdd10982-f498-45d6-b4d5-f7c0215a526a
> refactor: fetchHistory on sagas/nanoContract to avoid iteration suspension

- package-lock.json
- package.json
The previous version is breaking the build process.
- It must have the version 5.31.0 of @sentry/react-native pinned
> chore: update sentry version

- scripts/bump-version.js
The `bump-version` script was not updated after the latest change in our official versioning syntax.
- Fixes the release candidate increment on the bump version script
- The resulting version should be compliant with the change from #406
> fix: Bump script rc regex

- android/build.gradle
- Implements a cherry pick of the same feature available on the Hathor Play branch: #562 
- The application build process should target Android SDK 34
- This is a part of the `0.28.0` Release Candidate
> feat: Android target 34

- package.json
- src/actions.js
- src/reducers/reducer.js
- src/sagas/reown.js
- src/sagas/wallet.js
- src/screens/MainScreen.js
- src/screens/Settings.js
- We should disable reown when the network does not support nano contracts
- We should add a missing key in allow-scripts
> feat: reown on nano contracts

- android/app/build.gradle
- ios/HathorMobile.xcodeproj/project.pbxproj
- package-lock.json
- package.json
> chore: bumped to v0.29.0-rc.1

- src/sagas/tokens.js
- Fetch token metadata is failing because we don't have `serverInfo` when on the wallet-service facade
- We should use the network from networkSettings
> fix: fetch metadata fail

- package.json
- pre_release.sh
- src/sagas/featureToggle.js
- src/sagas/reown.js
- src/screens/PinScreen.js
- We should stop crashing when coming back from an app `inactive` state
- We should send the error to Sentry when the biometry fails to migrate
- We should update the release script to use `npm run setup`
- We should add improved logs on feature toggle saga
> fix: reown crashing

- src/reducers/reducer.js
- src/screens/PinScreen.js
- src/screens/Security.js
- src/store.js
- src/utils.js
> fix: safe biometry state

- src/sagas/wallet.js
- `firstAddress` is fetched from the state and it never gets updated when changing networks.
> fix: request first address on wallet start success

- src/sagas/reown.js
- Reown would freeze after a failure in create nano contract RPC request because it was expecting an action that was never fired
> fix: race with the correct actions in create transaction saga

- src/sagas/ses.js
- The feature toggle listener should end if the platform is android, this will prevent apps from restarting when ses is disabled.
> fix: kill the feature toggle update listener task if android

- android/app/build.gradle
- ios/HathorMobile.xcodeproj/project.pbxproj
- package-lock.json
- package.json
> chore: bump to v0.30.1-rc.1

- Makefile
- scripts/bump-version.js
Recently we had issues using the bump script to generate the release candidate for a new version: the process had to be done in two steps, one for the actual version bump and another for the release candidate for that version. That had the downside of bumping the android build version twice, which required manual intervention to fix.
With the changes from this PR, a single call will bump the version ( major, minor or patch ) and simultaneously initiate a release candidate version.
- The bump script should have an option to increment the release candidate version while also incrementing other semver version.
Example usage:
```sh
`3.0.1` -> make bump updateType=major -> `4.0.0`
`3.0.1` -> make bump updateType=major bumpRc=true -> `4.0.0-rc.1`
`3.0.1` -> make bump updateType=minor …
```
> feat: rc on bump version script

- src/screens/InitWallet.js
There were two events that triggered the validation of the words on the "Import Wallet" screen:
- Clicking the "Next" button at the bottom of the screen
- Clicking the native "Submit" button from the TextArea.
Each of these events had their own validation, which led to inconsistent app behavior and crashes when using the "Submit" button.
- In the "Import Wallet" screen, user must not receive an error by clicking "Submit" with an empty text
- Also must not receive an error with invalid words
https://github.com/user-attachments/assets/f0cc8b56-ae82-4a48-acb0-a27196e6a239
> fix: Crash on invalid words

- src/components/Reown/NanoContract/NewNanoContractTransactionRequest.js
After a send nano contract success, if you stay in the success screen and attempt to register a new nano contract, the register will fail until the app is restarted.
- We should be able to register nano contracts after a success
> fix: sequential nano contract register fails on second one

- README.md
- locale/da/texts.po
- locale/pt-br/texts.po
- locale/ru-ru/texts.po
- locale/texts.pot
- src/config.js
- src/screens/CreateTokenAmount.js
- src/screens/CreateTokenConfirm.js
- Removes duplicated "HTR" Symbol from the create token screen
- Replaces hardcoded "HTR" symbol with the dynamic value for the native token
- Deprecates obsolete "Default Token" property from the wallet config file.
- Updates the readme instructions on how to update the translation files
> fix: duplicated HTR symbol

- src/components/AmountTextInput.js
- src/components/NewPaymentRequest.js
- src/screens/CreateTokenAmount.js
- src/screens/CreateTokenConfirm.js
- src/screens/SendAmountInput.js
- src/screens/SendConfirmScreen.js
- src/utils.js
- We should use decimal places from the serverInfo instead of using the constant one
- We should refactor AmountTextInput to be a functional component
> refactor: decimal places

- locale/pt-br/texts.po
- scripts/update_translations.js
- The language `pt-br` must have all translations completed to pass the CI validation
- There should be a way for the developer to set arbitrary languages to this validation locally in dev environment
> chore: Add `pt-br` as a mandatory language on CI

- src/screens/Dashboard.js
- Resolves #668 
We could also remove the spacing entirely, but it wouldn't feel correct. See below
> fix: White bar below custom network

- pre_release.sh
- scripts/cleanup.sh
- scripts/cleanup_android.sh
- scripts/cleanup_ios.sh
When upgrading React Native versions, it's imperative to clean not only the local development folder but also the global caches for both Android and iOS at the operational system level. Failing to do so causes bugs with misleading messages that are hard to solve otherwise.
These scripts aim to facilitate this cleanup, providing the developer with a more reliable state upon which to start working.
Also, it's helpful to have this script run at pre-release, as it ensures the environment is as close as possible to that of the developer.
- Adds new cleanup scripts that also wipe global caches
- Incorporates those new scripts into the `pre_release.sh` script
> chore: Cleanup scripts

- ios/Podfile.lock
- package-lock.json
- package.json
When trying to build the app using the nix environment I was getting an error, which was fixed by the react native sentry upgrade (https://github.com/getsentry/sentry-react-native/issues/4715).
The nix environment is currently using pod v1.15.2, so I also updated the `Podfile.lock`.
- update react native sentry to v6.10.0
- update Podfile.lock
> chore: update react native sentry to v6.10.0

- src/sagas/nanoContract.js
- The nano contract history screen was crashing because it was trying to access `nc_pubkey` which doesn't exist anymore.
> fix: nano contract history was using nc_pubkey

- patches/@hathor+wallet-lib+2.6.0.patch
We were encountering many bigint conversion errors when retrieving API/websocket data due to schema parsing issues. The main problem is that in Android apps running with Hermes, the error messages are different from the expected ones.
- Add new error message handling as a patch for the wallet lib.
> fix: android big int double conversion errors have different message

- src/components/NanoContract/EditAddressModal.js
- src/components/NanoContract/NanoContractDetailsHeader.js
- src/components/NanoContract/SelectAddressModal.js
https://github.com/user-attachments/assets/2cca18db-8760-4c12-9131-a2f7be45b722
- We should remove the delay before showing children in the BackdropModal as it was not benefiting us in any way and was causing the `SelectAddressModal` to display a small modal before rendering the full content.
- We should change the `SelectAddressModal` modal in NanoContractDetail screen to only show one modal at a time, preventing nested modals which were causing react-native to break
- We should increase the SelectAddressModal size so it's the same size of all other modals
> fix: multiple modal nc address seletor

- package-lock.json
- package.json
- We must update `hathor-rpc-handler` to `2.2.0`
> chore: update rpc lib

- flake.nix
- src/reducers/reducer.js
- src/screens/PaymentRequestDetail.js
In some hard-to-define cases the Payment Request QR Code was crashing the app. This happened because the `token` object passed as parameter had the `balances` populated in it, containing bigint values.
Since those values are not necessary for the QR generation, they were simply removed from redux through the reducer.
- Fixes a BigInt issue happening when a Payment Request QR Code was being built
- Adjusts the Flake nix file to also work in Linux distros
> fix: Payment request bigint issues

- src/components/BackdropModal.js
- src/components/NanoContract/NanoContractDetails.js
- src/components/NanoContract/SelectAddressModal.js
- src/sagas/wallet.js
https://github.com/HathorNetwork/hathor-wallet-mobile/issues/727
The `SelectAddressModal` screen was calling `selectAddressAddressesRequest` in a `useEffect` and this component was used by the `BaseNanoContractRequest`, which is also calling `selectAddressAddressesRequest`. This by itself was a bug, we were calling the same method twice.
However, the `BaseNanoContractRequest` re-renders changing its content after the user types the PIN, so the screen can show a loading while the transaction is mined and sent to the network. After the loading, we show a `SuccessFeedbackScreen` and call `dispatch(statusConfig.setReadyAction());` which once again re-renders the   `BaseNanoContractRequest` component and makes `SelectAddressModal` component to mount again and call …
> fix: fetch all addresses should be called only once for the send nano reown screen

- src/constants.js
- src/screens/NetworkSettings/NetworkPreSettingsScreen.js
Nano testnet bravo is outdated because the latest full node version is not compatible with it. All nano tests are already happening in the hotel testnet, so we can remove it from the pre settings screen to make it cleaner.
- Remove nano bravo testnet from network pre settings screen
> feat: remove nano bravo testnet from network pre settings screen
