.eslintrc
changelogs/unreleased/feat-token-deposit.md
src/App.js
src/components/HathorHeader.js
src/components/InfoBox.js
src/constants.js
src/screens/CreateTokenAmount.js
src/screens/CreateTokenConfirm.js
src/screens/CreateTokenDepositNotice.js
src/screens/CreateTokenName.js
src/screens/CreateTokenSymbol.js
src/screens/InitWallet.js
src/screens/RegisterTokenManual.js
src/utils.js

feat: token deposit

---

.eslintrc
package-lock.json
package.json

Fix this issue: https://github.com/HathorNetwork/hathor-wallet-mobile/issues/13

fix: updating react native version to work with new xcode 11

---

src/screens/UnregisterToken.js

feat: handling error when unregistering a token

---

package-lock.json
package.json
src/App.js
src/screens/BackupWords.js
src/screens/InitWallet.js

Closes https://github.com/HathorNetwork/hathor-wallet-mobile/issues/23

feat: creating words backup screen

---

Makefile
i18nInit.js
locale/da/texts.po

feat(i18n): Add Danish translation

---

Makefile
i18nInit.js
locale/ru-ru/texts.po

The translation was done by an anonymous external contributor.

feat(i18n): Add Russian translation

---

src/store.js

Description of this issue on https://github.com/HathorNetwork/hathor-wallet-mobile/issues/52

fix: no need to save wallet data in the persistent storage

---

src/screens/LoadHistoryScreen.js
src/screens/PinScreen.js

fix: removing xpub migration from walletData and getting it from xpriv

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

Fix wrong hathor-wallet-lib published in both App Store and Google Play.

Bump up to v0.9.4

---

locale/da/texts.po

Translations made by @InfiniteDAGl00p

chore: adding danish translation for sentences on error modal

---

android/app/build.gradle
android/app/src/main/java/com/hathormobile/MainApplication.java
android/gradle.properties
android/settings.gradle
ios/Podfile
ios/Podfile.lock
locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
package-lock.json
package.json
src/actions.js
src/reducer.js
src/screens/Settings.js
src/utils.js

The user must be able to share his device's unique identifier and Hathor team should be able to use it to fix his device on the new wallet facade

feat: using device unique identifier on unleash and screen to share it

---

package-lock.json
package.json
src/actions.js
src/components/AmountTextInput.js
src/components/NewPaymentRequest.js
src/components/TokenDetails.js
src/components/TokenSelect.js
src/components/TxDetailsModal.js
src/constants.js
src/reducer.js
src/screens/ChangeToken.js
src/screens/CreateTokenConfirm.js
src/screens/Dashboard.js
src/screens/MainScreen.js
src/screens/PaymentRequestDetail.js
src/screens/RegisterTokenManual.js
src/screens/SendAmountInput.js
src/screens/SendConfirmScreen.js
src/screens/TokenDetail.js
src/screens/UnregisterToken.js
src/utils.js

feat: show NFT amount as integer and allow only sending integers as well

---

QA.md
locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
package-lock.json
package.json
src/App.js
src/actions.js
src/reducer.js
src/screens/ChangePin.js
src/screens/LoadHistoryScreen.js
src/screens/PinScreen.js
src/screens/RecoverPin.js
src/screens/ResetWallet.js
src/utils.js
yarn.lock

- Should fix https://github.com/HathorNetwork/internal-issues/issues/62
- Depends on https://github.com/HathorNetwork/hathor-wallet-lib/pull/291

fix: change pin should update storage data that depends on the password

---

package-lock.json
package.json
src/actions.js
src/constants.js
src/reducer.js

- The new wallet service facade should receive new transactions and transactions updates in real-time
- The new wallet service facade should properly update balances and transaction history when a new tx is received or a tx is updated

feat: added websocket support for wallet service facade

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump v0.14.0

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump to v0.15.0

---

src/actions.js
src/errorHandler.js
src/reducer.js
src/screens/SendConfirmScreen.js

- Fix unnecessary linter warnings

refactor: solve warnings

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json
src/actions.js
src/errorHandler.js
src/reducer.js
src/screens/LoadHistoryScreen.js
src/screens/SendConfirmScreen.js

Release v0.16.0

---

android/app/src/main/java/com/hathormobile/HTRReloadBundleModule.java
android/app/src/main/java/com/hathormobile/HTRReloadBundlePackage.java
android/app/src/main/java/com/hathormobile/MainApplication.java
android/app/src/main/java/com/hathormobile/ReactInstanceHolder.java
ios/HTRReloadBundleModule/HTRReloadBundleModule.h
ios/HTRReloadBundleModule/HTRReloadBundleModule.m
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json
src/actions.js
src/constants.js
src/featureFlags.js
src/screens/LoadHistoryScreen.js

- The app must listen for changes on the unleash feature flag provider
- The app must fall back to the old facade in case the start wallet fails while using the wallet service facade

feat: listen unleash for changes 

---

QA.md

- QA must include a step to test the wallet on the wallet service facade
- QA must include a step to make sure https://github.com/HathorNetwork/hathor-wallet-lib/pull/332 won't happen

docs: update qa

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bumped to version 0.17.0

---

QA.md
android/app/build.gradle
android/app/src/main/java/com/hathormobile/HTRReloadBundleModule.java
android/app/src/main/java/com/hathormobile/HTRReloadBundlePackage.java
android/app/src/main/java/com/hathormobile/MainApplication.java
android/app/src/main/java/com/hathormobile/ReactInstanceHolder.java
ios/HTRReloadBundleModule/HTRReloadBundleModule.h
ios/HTRReloadBundleModule/HTRReloadBundleModule.m
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json
src/actions.js
src/constants.js
src/featureFlags.js
src/screens/LoadHistoryScreen.js

Release v0.17.0

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump to v0.17.1

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

Release v0.17.1

---

README.md

[release] docs: improve readme (#160)

---

src/App.js

- Enable fingerprint and face id biometry options

feat: Biometry options

---

QA.md
src/actions.js
src/utils.js

- Change the Keychain password when changing the pin
This closes #170

fix: reset biometry on pin change

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump to v0.18.0

---

src/actions.js

- Wallet service facade should be correctly instantiated after lib upgrade. New class signature: https://github.com/HathorNetwork/hathor-wallet-lib/blob/master/src/wallet/wallet.ts#L114

fix: using new constructor signature for wallet service facade

---

src/App.js

- Add warning that changing user agent might break other services

chore: add warning in the user agent set not to change it

---

locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot

- We should include missing translations from the async-load-tokens feature PR

chore: updated locale

---

src/reducer.js

- When the token history is loading, we won't have the `data` array, so we need to have a fallback to it on realtime updates

fix: potential crash when receiving a transaction for a token that is currently loading

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump v0.19.0

---

README.md
android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
package-lock.json
package.json
src/App.js
src/actions.js
src/components/Spinner.js
src/components/TokenSelect.js
src/featureFlags.js
src/reducer.js
src/sagas/helpers.js
src/sagas/index.js
src/sagas/tokens.js
src/sagas/wallet.js
src/screens/CreateTokenAmount.js
src/screens/Dashboard.js
src/screens/LoadHistoryScreen.js
src/screens/LoadWalletErrorScreen.js
src/screens/MainScreen.js
src/screens/SendAmountInput.js
src/screens/SendConfirmScreen.js
src/utils.js

Release v0.19.0

---

README.md
WINDOWS.md

- Instructions to run mobile wallet on Windows.

docs: add windows instructions to run mobile wallet

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump v0.19.1

---

README.md
WINDOWS.md
android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json
src/actions.js
src/sagas/wallet.js
src/screens/LoadHistoryScreen.js
src/screens/RegisterTokenManual.js
src/utils.js

Release v0.19.1

---

src/constants.js

Updated Url

---

docs/UNLOCK_MECHANISM.md

- We should have a document describing what happens during a unlock on the mobile app

docs: unlock mechanism

---

src/App.js

- We should handle properly the active to active state transition on the method `handleAppStateChange`, as described in https://github.com/HathorNetwork/internal-issues/issues/144

fix: handle app state change

---

locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
src/constants.js
src/screens/About.js
src/screens/InitWallet.js

- Add terms of service and privacy policy to the welcome and about screens
- Translate to portuguese the new sentences

feat: add terms of service and privacy policy to the welcome and about screens

---

package-lock.json
package.json

- Upgraded wallet-lib to v0.43.0

chore: upgraded wallet lib to v0.43.0

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump to v0.20.0

---

src/components/CopyClipboard.js
src/components/HathorList.js
src/components/TxDetailsModal.js

- add a way to easily copy the transaction id
Closes #80

feat: add button to copy transaction id

---

src/App.js
src/actions.js
src/reducer.js
src/sagas/wallet.js
src/screens/ChoosePinScreen.js
src/screens/LoadHistoryScreen.js
src/screens/LoadWalletErrorScreen.js
src/screens/PinScreen.js

refactor: better load flow

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump to v0.22.0

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bumped to v0.22.1

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
package-lock.json
package.json
src/actions.js
src/components/ReceiveMyAddress.js
src/reducer.js
src/sagas/wallet.js
src/screens/Settings.js

Release v0.22.1

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
locale/da/texts.po
package-lock.json
package.json
src/constants.js
src/featureFlags.js
src/sagas/wallet.js
src/screens/LoadWalletErrorScreen.js
src/screens/PinScreen.js

- fix: small typo on danish translation for displaying time
- feat: wallet now loads from the stored encrypted xpriv to improve loading time on the wallet-service
- feat: using new wallet-service feature flag schema
- Release v0.23.0

Release v0.23.0

---

package-lock.json
package.json

- Update hathor-lib to version 0.45.0

chore: update hathor-lib to 0.45.0

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump 0.24.0

---

RELEASING.md

- Update the bumping instructions in RELEASE.md

docs: update bumping instructions in RELEASE.md

---

ios/HathorMobile/Info.plist
ios/Podfile
src/workers/backgroundListeners.js

- add lacking iOS pod dependencies
- disable firebase auto initialization
- add guard in the firebase background listener initialization

fix: push notification initialization for iOS

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump 0.24.1

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

- bump 0.24.2
- fix tx details modal overflow on pin screen

chore: bump 0.24.2

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump v0.24.3

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump 0.25.0

---

src/screens/RegisterTokenManual.js

- Generalize token validation in order to use the "register token" feature with `testnet` network

feat: generalize token validation

---

ios/HathorMobile/Info.plist

- Configure background processing permission on iOS

chore: configure background processing permission on iOS

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bump v0.26.0-rc1

---

src/constants.js
src/sagas/helpers.js
src/sagas/pushNotification.js
src/sagas/tokens.js
src/sagas/wallet.js
src/screens/DecideStackScreen.js
src/screens/PinScreen.js
src/store.js
src/utils.js
src/workers/pushNotificationHandler.js

- Do not use `for await` syntax in any saga.
- Create a `HybridStore` that extends `MemoryStore` but with a persistent access data.
- Remove features specififc to the `LevelDBStore`
- Remove `fromXpriv` argument from start wallet saga
- Fix issues found when debugging the app.
- TxHistory contructor expects `isVoided`
- fix storage initialization for new wallets
- use new operator on address class initialization
- fix typo on `numberUtils` helpers

feat: custom async storage store

---

package-lock.json
package.json

- Bump wallet-lib version to v1.0.0-rc5

chore: bump wallet lib v1.0.0-rc5

---

src/App.js
src/actions.js
src/components/QRCodeReader.js
src/reducer.js
src/sagas/index.js
src/sagas/permissions.js
src/screens/SendScanQRCode.js

- Camera permissions should be requested through saga instead of directly on a screen
- "Register Token" screen should go directly to "Manual Input" when camera permission is blocked

refactor: Saga camera permissions

---

src/screens/PinScreen.js

- Fix PinScreen lateral color difference on some devices
- Avoid flickering the Pin Digits while waiting for the biometry results from OS

fix: Pin screen adjustments

---

src/store.js

- Allow the wallet to be reset successfully

fix: reset wallet

---

src/App.js
src/components/AmountTextInput.js
src/components/HathorHeader.js
src/components/SimpleInput.js
src/screens/Settings.js
src/styles/init.js
src/styles/themes.js

Solves items from #318 
- Fixes colors that were off on the iOS version of the app. Details below.
- Implements the [Themes feature](https://reactnavigation.org/docs/themes/) of React Navigation v6
Below are some demonstrations of the changes. Click to enlarge the images.
| Screen | Old v0.25.0<br/><sub>Android device</sub> | Android<br/><sub>Simulator</sub> | iOS<br/><sub>Simulator</sub> |
|---|---|---|---|
| Dashboard | ![01 - Dashboard - v25](https://github.com/HathorNetwork/hathor-wallet-mobile/assets/1299409/3b1706d1-58eb-40a7-9549-6ec07bc1c1b3) | ![01 - Dashboard - Android](https://github.com/HathorNetwork/hathor-wallet-mobile/assets/1299409/b63cbb6f-a641-43be-a908-3f6209d3c77c) | ![01 - Dashboard - iOS](https://github.com/HathorNetwork/hathor-wallet-mobile/assets/1299409/aee1473e-56 …

Fix: iOS Colors

---

src/App.js
src/screens/NetworkSettings/NetworkSettingsFlowStack.js
src/screens/NetworkSettings/index.js
src/screens/Settings.js

- feat: add NetworkSettingsFlowStack
>[!NOTE]
> I edited the commit that add NetworkSettingsFlowStack to remove the module alias.
Remove the commits related to:
- chore: add babel-plugin-module-resolver@5.0.0
- babel: configure @components and @screens module aliases

(6) feat: add network settings flow stack

---

src/screens/NetworkSettings/NetworkSettingsDisclaimerScreen.js
src/screens/NetworkSettings/NetworkSettingsFlowStack.js

- Add disclaimner screen
>[!NOTE]
>I edited some commits to remove module aliases.
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/037dc923-e64e-4078-9e96-7d8911f5a242

(7) feat: add disclaimer screen

---

src/constants.js
src/sagas/index.js
src/screens/NetworkSettings/NetworkPreSettingsScreen.js
src/screens/NetworkSettings/NetworkSettingsFlowStack.js

- add mainnet and testnet explorer-service URLs
- add networkSettingsSaga to the sagas list
- add NetworkPreSettingsScreen
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/d60a87e5-3fb2-4418-a9ea-ad05c6dbe1e1

(8) feat: add presettings screen

---

src/sagas/helpers.js

- get the correct data
- add a strictier status validation to only consider HTTP status code 200

(9) fix: getWalletServiceNetwork function

---

src/actions.js
src/constants.js
src/reducers/reducer.js
src/sagas/helpers.js
src/sagas/networkSettings.js
src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
src/screens/NetworkSettings/NetworkPreSettingsScreen.js
src/screens/NetworkSettings/NetworkSettingsFlowStack.js

- feat(wip): add CustomNetworkSettingsScreen
- feat: add warning message container
- feat: add feedback modals based on network settings status
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/8f1e09d4-394b-46aa-87d4-9ee75e6c54c8

(10) feat: add custom network settings screen

---

src/screens/NetworkSettings/NetworkSettingsDisclaimerScreen.js
src/screens/NetworkSettings/NetworkSettingsFlowStack.js

- Conditional initialization of network settings flow stack

(11) feat: set correctly the NetworkSettingsFlowStack

---

src/screens/NetworkSettings/NetworkPreSettingsScreen.js
src/screens/NetworkSettings/helper.js

- Add feedback modal to presettings screen
- Extract helper for network settings
>[!NOTE]
>I edited the commit to remove module aliases.
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/bfd7017f-9246-409c-bbcb-747059fe31e4

(13) feat: add feedback modal to presettings screen

---

locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot

- update localization for ru-ru, da and pt-br
- translate the terms for pt-br

(16) feat: update localization

---

src/components/ToplineBar.js

- Fix ToplineBar component, base of NetworkStatusBar, by removing the height style: this produce the effect of not cut the text.

fix: ToplineBar component

---

Makefile
RELEASING.md
scripts/bump-version.js

- Adds a script that automates the bumping process

Chore: Version bump helper

---

locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
src/actions.js
src/constants.js
src/sagas/networkSettings.js
src/screens/NetworkSettings/CustomNetworkSettingsScreen.js

This change sets the txMiningUrl in the wallet lib configurations and a
presettings or custom network is selected.
- Add Tx Mining Service URL field in the form of Custom Network view
- Add TX_MINING_SERVICE_\<NETWORK\>_URL constants
- Add txMiningServiceUrl in presettings and in the redux networkSettings
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/4d3b6ebf-80b4-445a-b141-ed9164b5599c

feat: add txMiningServiceUrl to network settings

---

src/constants.js
src/sagas/featureToggle.js
src/screens/Settings.js

- It enables/disables the Network Settings option in the Settings screen
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/62debe03-c76c-4bf6-9e61-998302e10061

feat: add network-settings.rollout feature toggle

---

Makefile
RELEASING.md
android/app/build.gradle
firebase.json
ios/HathorMobile.xcodeproj/project.pbxproj
ios/HathorMobile/AppDelegate.mm
ios/HathorMobile/Info.plist
ios/Podfile.lock
locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
package-lock.json
package.json
scripts/bump-version.js
src/actions.js
src/constants.js
src/logger.js
src/reducers/reducer.js
src/sagas/featureToggle.js
src/sagas/networkSettings.js
src/sagas/pushNotification.js
src/screens/About.js
src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
src/screens/Settings.js
src/utils.js
src/workers/backgroundListeners.js

- New developer tool: "Bump helper"
- Adds `txMiningServiceUrl` to network settings
- Adds feature toggle to network settings
- Fixes handling of invalid version on About screen
- Fix on custom network update
- Fix on Firebase initialization

Release version `v0.26.1`

---

.gitignore
pre_release.sh

- Add `release.sh` to be run when starting a new release.

chore(release): Add release script

---

.github/workflows/main.yml

- Changing the ci process to run on new release branch

chore(ci): update to run on release branch

---

.github/workflows/main.yml
.gitignore
flake.lock
flake.nix
pre_release.sh
scripts/check_version
src/sagas/featureToggle.js
src/screens/CreateTokenAmount.js
src/screens/Receive.js
src/screens/SendAmountInput.js

This is not a release.
The changes in dev will be merged into master and dev will be deleted.

Merge dev changes into master

---

src/sagas/pushNotification.js

- Should fix open operation of a push notification
Error found while testing push notification on #424.
Error after tap on push notification message:
<image src="https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/f29dcd4c-b1c0-4fc8-af58-ad5c83cd3276" height="600"></image>
Fix:
<image src="https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/fa555b41-f752-45b3-bfc1-857fdef7bcac" height="600"></image>

fix: isTokenRegistered call from getTxDetails

---

src/sagas/wallet.js

- We should send more errors to sentry on the wallet saga

feat: sending more exceptions on load wallet to sentry

---

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/release_candidate_pr_template.md
locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
package-lock.json
package.json
src/App.js
src/actions.js
src/components/AskForPushNotification.js
src/components/TokenSelect.js
src/config.js
src/constants.js
src/reducers/reducer.js
src/sagas/errorHandler.js
src/sagas/featureToggle.js
src/sagas/helpers.js
src/sagas/pushNotification.js
src/sagas/tokens.js
src/sagas/wallet.js
src/screens/LoadHistoryScreen.js
src/screens/UnregisterToken.js

[//]: # (This should be discussed in the daily meeting)
[//]: # (Remember to bump the version to the next release candidate after this is merged)
Related to: https://github.com/HathorNetwork/internal-issues/issues/249
- fix: PinScreen dismiss response
- fix: exits script after dispatch failure effect
- fix: replace BLOCKED to DENIED enum value
- fix: push notification authorization logic
- fix: push notification opt-in modal render time
- refactor: feature toggle using hathor unleash client
- refactor: reset wallet service ignore flag
- fix: isTokenRegistered call from getTxDetails
- feat: sending more exceptions on load wallet to sentry
- fix: token duplication on dashboard
- minor fixes and chores to improve readability
Start the release candidate process for version `0.27.0-rc.1`.
This …

release-candidate: 0.27.0-rc.1

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

Related to: https://github.com/HathorNetwork/internal-issues/issues/249
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/406
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/407
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/417
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/419
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/421
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/422
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/423
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/424
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/426
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/428
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/430
- …

bump: v0.27.0-rc.1

---

src/actions.js
src/constants.js
src/sagas/helpers.js
src/sagas/tokens.js
src/sagas/wallet.js

[//]: # (This should be discussed in the daily meeting)
[//]: # (Remember to bump the version to the next release candidate after this is merged)
- feat: add nano contract feature toggle (#441)
- fix: missing transaction after reload (#442)
- fix: wallet-service network error (#444)
Start the release candidate process for version `0.27.0-rc.2`.
This PR will merge any changes on `master` into `release-candidate` branch.

release: v0.27.0-rc.2

---

__tests__/sagas/nanoContracts/registerNanoContract.test.js
__tests__/sagas/networkSettings.test.ts
jest.config.js
locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
src/actions.js
src/constants.js
src/reducers/reducer.js
src/sagas/nanoContract.js
src/store.js

Related to: https://github.com/HathorNetwork/rfcs/pull/72
- should create sagas/nanoContract.js
- should add registerNanoContract saga effect
- should persist registered Nano Contract
- should update store with registered Nano Contract
- should unit test registerNanoContract saga and its components
>[!WARNING]
>This PR depends on:
>- https://github.com/HathorNetwork/hathor-wallet-lib/pull/614
>- https://github.com/HathorNetwork/hathor-wallet-lib/pull/604
>- https://github.com/HathorNetwork/hathor-wallet-lib/pull/603
>- https://github.com/HathorNetwork/hathor-wallet-lib/pull/606
>- https://github.com/HathorNetwork/hathor-wallet-lib/pull/605

feat: add registerNanoContract saga effect

---

src/sagas/helpers.js
src/sagas/networkSettings.js
src/sagas/tokens.js

It helps to debug in case of error investigation.
- chore: add instrumentation to sagas/networkSettings
- chore: add instrumentation to sagas/helpers
- chore: add instrumentation on sagas/tokens

chore: improve instrumentation on sagas

---

src/actions.js
src/reducers/reducer.js
src/sagas/networkSettings.js
src/sagas/wallet.js
src/screens/Settings.js

Issues found on QA for v0.27.0-rc.3
Closes: https://github.com/HathorNetwork/hathor-wallet-mobile/issues/464
- It should fix network settings processing on wallet
- It should fix wallet behavior consistency regarding custom network settings

fix: custom network settings processing

---

package-lock.json
package.json

- it should bump the dependency hathor-wallet-lib to v1.5.0

bump: wallet-lib to v1.5.0

---

QA_CUSTOM_NETWORK.md
QA_PUSH_NOTIFICATION.md

- It should update the QA documents of Push Notification and Custom Settings Network

chore: update QA docs

---

package-lock.json
package.json
src/actions.js
src/config.js
src/sagas/helpers.js
src/sagas/wallet.js
src/screens/CreateTokenAmount.js
src/screens/MainScreen.js
src/screens/UnregisterToken.js

- Bump wallet-lib v1.8.0
- Fix instances of any breaking changes, i.e. uses of `HATHOR_TOKEN_CONFIG`

chore: upgrade wallet lib to v1.8.0

---

src/constants.js
src/sagas/networkSettings.js
src/sagas/tokens.js
src/sagas/wallet.js

- It should declare `txMiningServiceUrl` on customNetwork payload to update the state on redux store
- It should config `txMiningServiceUrl` and `explorerServiceUrl` on wallet initialization, prior to the wallet start command
- it should fix network identification on network settings update
- It should filter out HTR token from fetch balance over registered tokens iteration
- It should improve saga/tokens instrumentation to make debug easier
The following demo was recorded after applying this fix to the `feat/rpc-lib-integration` branch.
https://github.com/HathorNetwork/hathor-wallet-mobile/assets/5992210/ca9f9534-c83c-4d37-80c0-46de2e9590d6

fix: txMiningServiceUrl lack of declaration on customNetwork

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/508
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/507

bump: v0.27.2

---

src/components/TxDetailsModal.js

- Remove Nano Contract status from Tx Details Modal

refactor: remove nc status from tx details

---

src/config.js
src/constants.js

- Set EventCoin as default token alongside with Hathor token

feat: add event coin token as default alongside with hathor

---

src/screens/InitWallet.js

feat: improve text input type

---

src/sagas/featureToggle.js

- We should always send `HathorDemo` as the userId to Unleash so we have better control over which features are enabled in HathorPlay

refactor: hardcoded userid

---

src/components/WalletConnect/NanoContract/NewNanoContractTransactionRequest.js

- Fix error when registering nano contract from new nano contract transaction screen
- Request a first address when nano contract is not registered to be used in nano contract registration
https://github.com/user-attachments/assets/9f71eef8-2830-4ae4-b1d1-e22692af48bd
Show instruction to register the Nano Contract and cancel action only.

fix: register new nano contract from request screen

---

src/components/WalletConnect/NanoContract/NewNanoContractTransactionRequest.js

- Unify unmount callback on new nano contract transaction request component
- Restore nano contract transaction status to ready on unmount

fix: unify unmount as only one is called per component

---

pre_release.sh

1. Add the git commit information to the `pre_release.sh`.

chore: Add git commit information to the pre-release script output

---

src/components/WalletConnect/NanoContract/NewNanoContractTransactionRequest.js

- Change state to ready when navigating to success screen

fix: wrong success navigation by forcing ready state on navigation

---

src/sagas/nanoContract.js

The change address action for registered Nano Contract is brocken.
- Fix effect to change address for registered Nano Contract by using the correct param name newAddress

fix: change nc address by renaming the param to newAddress

---

QA_NANO_CONTRACT.md

- Add QA document for Nano Contract feature

feat: add QA for Nano Contract

---

locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
src/constants.js
src/screens/CreateTokenConfirm.js
src/screens/PinScreen.js
src/screens/Security.js
src/screens/SendConfirmScreen.js
src/store.js
src/utils.js

- Create a new safe biometry mode where the access data is not encrypted with the pin, but a 32 byte random password.
- Enable this biometry mode conditionally based on a feature flag.

feat: safe biometry mode

---

QA.md
QA_CUSTOM_NETWORK.md
QA_PUSH_NOTIFICATION.md

- Minor improvements to QAs, based on recent QAs https://github.com/HathorNetwork/internal-issues/issues/361 and https://github.com/HathorNetwork/internal-issues/issues/400
- Adds clarification of intermediate steps on some actions
- Adds an explicit verification of the Wallet Service state
- Removes an Unleash feature waiting test which is not implemented in the Push Notification tests
- Adds a second network transition to the Custom Network tests

docs: Minor improvements to QA

---

QA.md

- Update and QA steps on biometry to also test the new biometry mode.

Docs: improved pin security

---

src/constants.js
src/screens/NetworkSettings/NetworkPreSettingsScreen.js

- We should add the nano-testnet as an option on the custom networks page

feat: added nano-testnet as a network option on network settings

---

src/sagas/wallet.js
src/screens/PinScreen.js
src/utils.js

fix: safe biometry migration2

---

android/gradle.properties
patches/react-native+0.72.5.patch
src/sagas/ses.js

- We should disable SES and re-enable Hermes on android

chore: re-enable hermes and disable ses

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

- Bump to version v0.30.0-rc.1

chore: bumped to v0.30.0-rc.1

---

src/components/NewHathorButton.js
src/components/Reown/WarnDisclaimer.js
src/components/SimpleButton.js

**Before the fix:**
- Seed cutting off text
- Invisible reset wallet on android
**After the fix:**
- Seed not cutting off text
- Reset wallet visible:
- Fonts were being cut off on some devices

fix: button font size

---

locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
src/components/SimpleButton.js
src/screens/NanoContractRegisterQrCodeScreen.js

- We should fix a pinky-sized button in the register nano contract screen

fix: tiny button

---

pre_release.sh

1. Remove the `ios/Pods/` folder in the `pre_release.sh` script.

chore(pre-release): Remove all iOS Pods to force a fresh reinstall

---

src/config.js

- We should skip the initial confirmation modal

feat: skip reown confirmation modal

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/645
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/644
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/643
- https://github.com/HathorNetwork/hathor-wallet-mobile/pull/642

chore: bumped to v0.31.0

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

- #652
- #653
- #656
- #654
- #661
- #666
- #660
- #655
- #673
- #674
- #682

chore: bumps to v0.31.1-rc.1

---

locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
package-lock.json
package.json
src/components/BackdropModal.js
src/components/GlobalErrorModal.js
src/components/HathorModal.js
src/components/ModalBase.js
src/components/Reown/ApproveRejectModal.js
src/components/Reown/RequestConfirmationModal.js
src/components/TxDetailsModal.js
src/screens/BackupWords.js
src/screens/SendAmountInput.js
src/screens/SendConfirmScreen.js

https://github.com/user-attachments/assets/0585b116-1a03-420d-bb38-f261dab161d2
- We should remove `react-native-modal` which was causing screen flickering with the new navigation library
- We should extend the react-native modal to have all the features react-native-modal had
- We should fix `SendAmountInput` missing `decimalPlaces`

refactor: new modals

---

locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
package-lock.json
package.json
src/components/BackdropModal.js
src/components/CopyClipboard.js
src/components/GlobalErrorModal.js
src/components/HathorModal.js
src/components/ModalBase.js
src/components/Reown/ApproveRejectModal.js
src/components/Reown/NanoContract/BaseNanoContractRequest.js
src/components/Reown/NanoContract/NanoContractMethodArgs.js
src/components/Reown/NanoContract/SignedDataDisplay.js
src/components/Reown/RequestConfirmationModal.js
src/components/Reown/SignOracleDataRequest.js
src/components/Reown/theme.js
src/components/TxDetailsModal.js
src/screens/BackupWords.js
src/screens/SendAmountInput.js
src/screens/SendConfirmScreen.js

https://github.com/user-attachments/assets/d2504ebe-c179-40f7-93b8-d5099dd6582d
- We should update the UI for the htr_signOracleData RPC request to properly show the address (when it's an address)
- We should properly handle the SignedData arg type in the `sendNanoContractTx` and `sendNanoContractCreateTokenTx` modals.
- The screen IS flickering, but we will not attempt to fix it in this PR.

feat: updated sign oracle data

---

src/constants.js

- We should update the `nano-testnet` network

feat: bravo testnet

---

locale/da/texts.po
locale/pt-br/texts.po
locale/ru-ru/texts.po
locale/texts.pot
src/screens/SendConfirmScreen.js
src/screens/SendScanQRCode.js

- Transform in bigint the string amount from the qrcode reader
- Correctly show the amount balance in the Send Confirm screen

fix: transform amount str to bigint and show correct balance

---

src/components/FeedbackContent.js
src/components/HathorModal.js
src/components/NanoContract/NanoContractsList.js
src/components/PushTxDetailsModal.js
src/sagas/wallet.js

- fix: We should set serverInfo when on the wallet-service facade to fix a bug where the decimal places were not loaded
- fix: We should fix the padding on the push tx modal
- We should fix the `Register new` button size on the list nano contracts screen

fix: rc3 fixes

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bumps to v0.32.1

---

android/app/build.gradle
ios/HathorMobile.xcodeproj/project.pbxproj
package-lock.json
package.json

chore: bumps to v0.32.2-rc.1

---

src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
src/screens/NetworkSettings/NetworkPreSettingsScreen.js

- Redirect to Dashboard after network settings update success
https://github.com/user-attachments/assets/d99fdfb1-dea5-4b36-9433-ac269118190c

feat: redirect to Dashboard after network settings success

---

src/actions.js
src/components/BackdropModal.js
src/components/NanoContract/NanoContractDetails.js
src/components/NanoContract/SelectAddressModal.js
src/constants.js
src/reducers/reducer.js
src/sagas/featureToggle.js
src/sagas/networkSettings.js
src/sagas/wallet.js
src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
src/screens/NetworkSettings/NetworkPreSettingsScreen.js

[//]: # (This should be discussed in the daily meeting)
[//]: # (Remember to bump the version to the next release candidate after this is merged)
Start the release candidate process for version `0.33.0-rc.1`.
This PR will merge any changes on `master` into `release-candidate` branch.

Start release candidate v0.33.0-rc.1
